[workspace]
resolver = "2"

members = [
    "api",
    "api/types",
    "config",
    "config/generate-key",
    "config/global-constants",
    "config/management",
    "config/management/genesis",
    "config/management/network-address-encryption",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus",
    "consensus/consensus-types",
    "consensus/safety-rules",
    "crates/bounded-executor",
    "crates/channel",
    "crates/crash-handler",
    "crates/debug-interface",
    "crates/diem-assets-proof",
    "crates/diem-bitvec",
    "crates/diem-client",
    "crates/diem-crypto",
    "crates/diem-crypto-derive",
    "crates/diem-documentation-tool",
    "crates/diem-faucet",
    "crates/diem-id-generator",
    "crates/diem-infallible",
    "crates/diem-log-derive",
    "crates/diem-logger",
    "crates/diem-metrics",
    "crates/diem-metrics-core",
    "crates/diem-proptest-helpers",
    "crates/diem-rate-limiter",
    "crates/diem-rest-client",
    "crates/diem-retrier",
    "crates/diem-temppath",
    "crates/diem-time-service",
    "crates/diem-wallet",
    "crates/diem-workspace-hack",
    "crates/fallible",
    "crates/num-variants",
    "crates/proxy",
    "crates/short-hex-str",
    "crates/swiss-knife",
    "crates/transaction-emitter",
    "devtools/x",
    "devtools/x-core",
    "devtools/x-lint",
    "diem-move/df-cli",
    "diem-move/diem-events-fetcher",
    "diem-move/diem-framework",
    "diem-move/diem-framework/DPN/releases",
    "diem-move/diem-framework/experimental/demo-cli",
    "diem-move/diem-framework/experimental/releases",
    "diem-move/diem-framework/releases",
    "diem-move/diem-keygen",
    "diem-move/diem-resource-viewer",
    "diem-move/diem-transaction-benchmarks",
    "diem-move/diem-transactional-test-harness",
    "diem-move/diem-validator-interface",
    "diem-move/diem-vm",
    "diem-move/e2e-tests",
    "diem-move/e2e-tests-replay",
    "diem-move/e2e-testsuite",
    "diem-move/genesis-viewer",
    "diem-move/mvhashmap",
    "diem-move/parallel-executor",
    "diem-move/transaction-builder-generator",
    "diem-move/transaction-replay",
    "diem-move/vm-genesis",
    "diem-move/writeset-transaction-generator",
    "diem-node",
    "execution/db-bootstrapper",
    "execution/execution-correctness",
    "execution/executor",
    "execution/executor-benchmark",
    "execution/executor-test-helpers",
    "execution/executor-types",
    "json-rpc",
    "json-rpc/integration-tests",
    "json-rpc/types",
    "language/benchmarks",
    "language/move-analyzer",
    "language/move-binary-format",
    "language/move-binary-format/serializer-tests",
    "language/move-borrow-graph",
    "language/move-bytecode-verifier",
    "language/move-bytecode-verifier/bytecode-verifier-tests",
    "language/move-bytecode-verifier/invalid-mutations",
    "language/move-bytecode-verifier/transactional-tests",
    "language/move-command-line-common",
    "language/move-compiler",
    "language/move-compiler/transactional-tests",
    "language/move-core/types",
    "language/move-ir/types",
    "language/move-ir-compiler",
    "language/move-ir-compiler/move-bytecode-source-map",
    "language/move-ir-compiler/move-ir-to-bytecode",
    "language/move-ir-compiler/move-ir-to-bytecode/syntax",
    "language/move-ir-compiler/transactional-tests",
    "language/move-model",
    "language/move-prover",
    "language/move-prover/boogie-backend",
    "language/move-prover/bytecode",
    "language/move-prover/interpreter",
    "language/move-prover/interpreter/crypto",
    "language/move-prover/interpreter-testsuite",
    "language/move-prover/lab",
    "language/move-prover/move-abigen",
    "language/move-prover/move-docgen",
    "language/move-prover/move-errmapgen",
    "language/move-prover/mutation",
    "language/move-prover/test-utils",
    "language/move-prover/tools/spec-flatten",
    "language/move-stdlib",
    "language/move-symbol-pool",
    "language/move-vm/integration-tests",
    "language/move-vm/runtime",
    "language/move-vm/test-utils",
    "language/move-vm/transactional-tests",
    "language/move-vm/types",
    "language/testing-infra/module-generation",
    "language/testing-infra/test-generation",
    "language/testing-infra/transactional-test-runner",
    "language/tools/mirai-dataflow-analysis",
    "language/tools/move-bytecode-utils",
    "language/tools/move-bytecode-viewer",
    "language/tools/move-cli",
    "language/tools/move-coverage",
    "language/tools/move-disassembler",
    "language/tools/move-explain",
    "language/tools/move-package",
    "language/tools/move-resource-viewer",
    "language/tools/move-unit-test",
    "language/tools/read-write-set",
    "language/tools/read-write-set/dynamic",
    "language/tools/read-write-set/types",
    "mempool",
    "network",
    "network/builder",
    "network/discovery",
    "network/memsocket",
    "network/netcore",
    "network/socket-bench-server",
    "sdk",
    "sdk/compatibility",
    "sdk/offchain",
    "sdk/transaction-builder",
    "secure/key-manager",
    "secure/net",
    "secure/push-metrics",
    "secure/storage",
    "secure/storage/github",
    "secure/storage/vault",
    "shuffle/cli",
    "shuffle/move",
    "state-sync/diem-data-client",
    "state-sync/inter-component/consensus-notifications",
    "state-sync/inter-component/event-notifications",
    "state-sync/inter-component/mempool-notifications",
    "state-sync/state-sync-v1",
    "state-sync/state-sync-v2/data-streaming-service",
    "state-sync/state-sync-v2/state-sync-driver",
    "state-sync/state-sync-v2/state-sync-multiplexer",
    "state-sync/storage-service/client",
    "state-sync/storage-service/server",
    "state-sync/storage-service/types",
    "storage/accumulator",
    "storage/backup/backup-cli",
    "storage/backup/backup-service",
    "storage/diemdb",
    "storage/diemsum",
    "storage/inspector",
    "storage/jellyfish-merkle",
    "storage/schemadb",
    "storage/scratchpad",
    "storage/scratchpad-benchmark",
    "storage/state-view",
    "storage/storage-client",
    "storage/storage-interface",
    "storage/storage-service",
    "testsuite/diem-fuzzer",
    "testsuite/diem-fuzzer/fuzz",
    "testsuite/forge",
    "testsuite/forge-cli",
    "testsuite/generate-format",
    "testsuite/smoke-test",
    "testsuite/testcases",
    "types",
    "vm-validator",
]

# NOTE: default-members is the complete list of binaries that form the "production Diem codebase". These members should
# never include crates that require fuzzing features or test features. These are the crates we want built with no extra
# test-only code included.
#
# For more, see the "Conditional compilation for tests" section in documentation/coding_guidelines.md.
default-members = [
    "config/generate-key",
    "config/management/genesis",
    "config/management/operational",
    "config/seed-peer-generator",
    "consensus/safety-rules",
    "crates/diem-assets-proof",
    "crates/diem-faucet",
    "crates/diem-rate-limiter",
    "crates/swiss-knife",
    "diem-move/diem-framework",
    "diem-move/transaction-builder-generator",
    "execution/db-bootstrapper",
    "execution/execution-correctness",
    "language/move-analyzer",
    "language/move-ir-compiler",
    "language/move-prover",
    "language/move-prover/lab",
    "language/move-prover/mutation",
    "language/move-prover/tools/spec-flatten",
    "language/move-compiler",
    "language/move-stdlib",
    "language/tools/move-disassembler",
    "language/tools/move-bytecode-viewer",
    "language/tools/move-cli",
    "language/tools/move-coverage",
    "language/tools/move-unit-test",
    "diem-move/df-cli",
    "diem-move/diem-events-fetcher",
    "diem-move/diem-framework/experimental/demo-cli",
    "diem-move/genesis-viewer",
    "diem-move/transaction-replay",
    "diem-move/writeset-transaction-generator",
    "language/tools/move-explain",
    "diem-node",
    "sdk",
    "secure/key-manager",
    "storage/backup/backup-cli",
    "storage/diemsum",
    "storage/inspector",
]

[profile.release]
debug = true

[profile.bench]
debug = true

# Build guppy in opt mode so that x commands are faster.
[profile.dev.package.guppy]
opt-level = 3
